services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - host
  php:
    build: ./docker/php
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
    depends_on:
      - mysql
    networks:
      - host
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/mysql/lib/mysql:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d/task_db.sql:/docker-entrypoint-initdb.d/task.sql
    networks:
      - host
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - host
networks:
  host:
    driver: bridge